name: First Workflow

on:
  push:
    branches: ["main"]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Taking pull
        run: actions/checout@v3
    
      - name: Greetings
        run: echo "Welcome to my world"
  
