name: First Workflow

on:
  push:
    branches: ["main"]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Taking pull
        uses: actions/checkout@v3
        
      - name: Greetings
        run: echo "Welcome to my world"
  
