name: Make Build

on:
  push:
    branches: [ main ]

jobs:
  app-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4.2.2
        
      - name: instaling Node
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 22.x
          cache: 'npm'

      - name: Install Dependences
        run: npm install

      - name: Make build
        run: npm run build

      - name: save buid in artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
           name: buid
           path: out/
              
